services:
  usersdb:
    image: mysql
    container_name: users_db
    ports:
      - '3307:3306'
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_DATABASE: users_db
      MYSQL_ROOT_PASSWORD: root

  users:
    image: "nvthiet1995/users:latest"
    container_name: users-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "users"
      SPRING_DATASOURCE_URL: "jdbc:mysql://usersdb:3306/users_db"
      SPRING_PROFILES_ACTIVE: "prod"
    depends_on:
      usersdb:
        condition: service_healthy
